general:
  branches:
    ignore:
      - gh-pages

machine:
  timezone: Asia/Tokyo

dependencies:
  pre:
    - npm install
    - git config --global user.name "CircleCI"
    - git config --global user.email "circleci@example.com"

test:
  override:
    - ./dummy.sh

deployment:
  master:
    branch: master
    commands: 
      - git clone -b dev git@github.com:sadayuki-matsuno/redux-sample.git dev
      - cd dev && npm install
      - cd dev && git submodule add -f -b  gh-pages https://github.com/sadayuki-matsuno/redux-sample.git dist
      - rm -rf dev/dist/*
      - cd dev && NODE_ENV=production npm run compile
      - cd dev/dist && git add -A
      - cd dev/dist && git commit -m "[ci skip] publish"
      - cd dev/dist && git push origin gh-pages
