export const SELECT_BOOKSHELF_PATH = 'SELECT_BOOKSHELF_PATH'
export const INVALIDATE_BOOKSHELF = 'INVALIDATE_BOOKSHELF'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
