export const IS_VALID_FB_AUTH = 'IS_VALID_FB_AUTH'
export const IS_INVALID_FB_AUTH = 'IS_INVALID_FB_AUTH'
export const REQUEST_AUTH = 'REQUEST_AUTH'

export const SELECT_BOOKSHELF_PATH = 'SELECT_BOOKSHELF_PATH'
export const INVALIDATE_BOOKSHELF = 'INVALIDATE_BOOKSHELF'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'

export const REQUEST_URL = 'REQUEST_URL'
export const RECEIVE_URL = 'RECEIVE_URL'
