export const SELECT_BOOKSHELF_PATH = 'SELECT_BOOKSHELF_PATH'
export const INVALIDATE_BOOKSHELF = 'INVALIDATE_BOOKSHELF'
export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'

export const INVALIDATE_PREVIEW = 'INVALIDATE_PREVIEW'
export const REQUEST_PREVIEW = 'REQUEST_PREVIEW'
export const RECEIVE_PREVIEW = 'RECEIVE_PREVIEW'
